version: 0.2

phases:
  build:
    commands:
      - echo "Validating Spark script..."
      - python3 -m py_compile etl_job.py
      - echo "Invoking Lambda to trigger EMR step..."
      - aws lambda invoke --function-name trigger-emr --payload file://payload.json response.json
artifacts:
  files: []
