version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Uploading Spark job to S3"
      - aws s3 cp etl_job.py s3://etl-output-bucket-mhn/jobs/etl_job.py
artifacts:
  files:
    - lambda_function.py
