version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Packaging PySpark job..."
      - zip -r etl_job.zip etl_job.py

artifacts:
  files:
    - etl_job.zip
